name: React App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  setup_common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

  run_tests:
    runs-on: ubuntu-latest
    needs: [setup_common]

    steps:
      - name: Setup common
        uses: ./.github/actions/setup_common.yml

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  lint_and_format:
    runs-on: ubuntu-latest
    needs: [run_tests]

    steps:
      - name: Setup common
        uses: ./.github/actions/setup_common.yml

      - name: Install dependencies
        run: yarn install # Uses cached dependencies if available

      - name: Type check
        run: yarn type-check

      - name: Linting
        run: yarn lint

      - name: Code formatting
        run: yarn format

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [lint_and_format]

    steps:
      - name: Setup common
        uses: ./.github/actions/setup_common.yml

      - name: Install dependencies
        run: yarn install # Uses cached dependencies if available

      - name: Build app
        run: yarn build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: yarn deploy
